package mi.m4x.as;

enum TokenType {
    IDENTIFIER, NUMBER, PLUS, MINUS, MULTIPLY, DIVIDE, LEFT_PAREN, RIGHT_PAREN, EOF, COMMA, COLON,
    NOP, ADD, SUB, MUL, DIV, MOD, AND, OR, XOR, NOT, SHL, SHR, LOAD, STORE, LDI,
    BEQ, BNE, BLT, BGT, JMP, CALL, RET, PUSH, POP, HALT, ROL, ROR, SLT, SLE, SGT, SGE, MOV, IPT, OPT,
}
